/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	datadependencyv1alpha1 "volcano.sh/apis/pkg/apis/datadependency/v1alpha1"
	applyconfigurationdatadependencyv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/datadependency/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// DataSourceClaimsGetter has a method to return a DataSourceClaimInterface.
// A group's client should implement this interface.
type DataSourceClaimsGetter interface {
	DataSourceClaims(namespace string) DataSourceClaimInterface
}

// DataSourceClaimInterface has methods to work with DataSourceClaim resources.
type DataSourceClaimInterface interface {
	Create(ctx context.Context, dataSourceClaim *datadependencyv1alpha1.DataSourceClaim, opts v1.CreateOptions) (*datadependencyv1alpha1.DataSourceClaim, error)
	Update(ctx context.Context, dataSourceClaim *datadependencyv1alpha1.DataSourceClaim, opts v1.UpdateOptions) (*datadependencyv1alpha1.DataSourceClaim, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dataSourceClaim *datadependencyv1alpha1.DataSourceClaim, opts v1.UpdateOptions) (*datadependencyv1alpha1.DataSourceClaim, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*datadependencyv1alpha1.DataSourceClaim, error)
	List(ctx context.Context, opts v1.ListOptions) (*datadependencyv1alpha1.DataSourceClaimList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *datadependencyv1alpha1.DataSourceClaim, err error)
	Apply(ctx context.Context, dataSourceClaim *applyconfigurationdatadependencyv1alpha1.DataSourceClaimApplyConfiguration, opts v1.ApplyOptions) (result *datadependencyv1alpha1.DataSourceClaim, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, dataSourceClaim *applyconfigurationdatadependencyv1alpha1.DataSourceClaimApplyConfiguration, opts v1.ApplyOptions) (result *datadependencyv1alpha1.DataSourceClaim, err error)
	DataSourceClaimExpansion
}

// dataSourceClaims implements DataSourceClaimInterface
type dataSourceClaims struct {
	*gentype.ClientWithListAndApply[*datadependencyv1alpha1.DataSourceClaim, *datadependencyv1alpha1.DataSourceClaimList, *applyconfigurationdatadependencyv1alpha1.DataSourceClaimApplyConfiguration]
}

// newDataSourceClaims returns a DataSourceClaims
func newDataSourceClaims(c *DatadependencyV1alpha1Client, namespace string) *dataSourceClaims {
	return &dataSourceClaims{
		gentype.NewClientWithListAndApply[*datadependencyv1alpha1.DataSourceClaim, *datadependencyv1alpha1.DataSourceClaimList, *applyconfigurationdatadependencyv1alpha1.DataSourceClaimApplyConfiguration](
			"datasourceclaims",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *datadependencyv1alpha1.DataSourceClaim { return &datadependencyv1alpha1.DataSourceClaim{} },
			func() *datadependencyv1alpha1.DataSourceClaimList {
				return &datadependencyv1alpha1.DataSourceClaimList{}
			},
		),
	}
}
