/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	datadependencyv1alpha1 "volcano.sh/apis/pkg/apis/datadependency/v1alpha1"
	applyconfigurationdatadependencyv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/datadependency/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// DataSourcesGetter has a method to return a DataSourceInterface.
// A group's client should implement this interface.
type DataSourcesGetter interface {
	DataSources() DataSourceInterface
}

// DataSourceInterface has methods to work with DataSource resources.
type DataSourceInterface interface {
	Create(ctx context.Context, dataSource *datadependencyv1alpha1.DataSource, opts v1.CreateOptions) (*datadependencyv1alpha1.DataSource, error)
	Update(ctx context.Context, dataSource *datadependencyv1alpha1.DataSource, opts v1.UpdateOptions) (*datadependencyv1alpha1.DataSource, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dataSource *datadependencyv1alpha1.DataSource, opts v1.UpdateOptions) (*datadependencyv1alpha1.DataSource, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*datadependencyv1alpha1.DataSource, error)
	List(ctx context.Context, opts v1.ListOptions) (*datadependencyv1alpha1.DataSourceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *datadependencyv1alpha1.DataSource, err error)
	Apply(ctx context.Context, dataSource *applyconfigurationdatadependencyv1alpha1.DataSourceApplyConfiguration, opts v1.ApplyOptions) (result *datadependencyv1alpha1.DataSource, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, dataSource *applyconfigurationdatadependencyv1alpha1.DataSourceApplyConfiguration, opts v1.ApplyOptions) (result *datadependencyv1alpha1.DataSource, err error)
	DataSourceExpansion
}

// dataSources implements DataSourceInterface
type dataSources struct {
	*gentype.ClientWithListAndApply[*datadependencyv1alpha1.DataSource, *datadependencyv1alpha1.DataSourceList, *applyconfigurationdatadependencyv1alpha1.DataSourceApplyConfiguration]
}

// newDataSources returns a DataSources
func newDataSources(c *DatadependencyV1alpha1Client) *dataSources {
	return &dataSources{
		gentype.NewClientWithListAndApply[*datadependencyv1alpha1.DataSource, *datadependencyv1alpha1.DataSourceList, *applyconfigurationdatadependencyv1alpha1.DataSourceApplyConfiguration](
			"datasources",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *datadependencyv1alpha1.DataSource { return &datadependencyv1alpha1.DataSource{} },
			func() *datadependencyv1alpha1.DataSourceList { return &datadependencyv1alpha1.DataSourceList{} },
		),
	}
}
