/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	apisdatadependencyv1alpha1 "volcano.sh/apis/pkg/apis/datadependency/v1alpha1"
	versioned "volcano.sh/apis/pkg/client/clientset/versioned"
	internalinterfaces "volcano.sh/apis/pkg/client/informers/externalversions/internalinterfaces"
	datadependencyv1alpha1 "volcano.sh/apis/pkg/client/listers/datadependency/v1alpha1"
)

// DataSourceClaimInformer provides access to a shared informer and lister for
// DataSourceClaims.
type DataSourceClaimInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() datadependencyv1alpha1.DataSourceClaimLister
}

type dataSourceClaimInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDataSourceClaimInformer constructs a new informer for DataSourceClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDataSourceClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDataSourceClaimInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDataSourceClaimInformer constructs a new informer for DataSourceClaim type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDataSourceClaimInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatadependencyV1alpha1().DataSourceClaims(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatadependencyV1alpha1().DataSourceClaims(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatadependencyV1alpha1().DataSourceClaims(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatadependencyV1alpha1().DataSourceClaims(namespace).Watch(ctx, options)
			},
		}, client),
		&apisdatadependencyv1alpha1.DataSourceClaim{},
		resyncPeriod,
		indexers,
	)
}

func (f *dataSourceClaimInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDataSourceClaimInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *dataSourceClaimInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisdatadependencyv1alpha1.DataSourceClaim{}, f.defaultInformer)
}

func (f *dataSourceClaimInformer) Lister() datadependencyv1alpha1.DataSourceClaimLister {
	return datadependencyv1alpha1.NewDataSourceClaimLister(f.Informer().GetIndexer())
}
