apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-custom-labels-data-job
  namespace: default
spec:
  minAvailable: 1
  schedulerName: volcano
  plugins:
    ringsconfigmap:
      - "-configmap-labels"
      - '{"team":"ai","project":"ascend","environment":"production"}'
      - "-configmap-data"
      - '{"hccl.json":"{\"status\":\"ready\",\"nodes\":4,\"topology\":\"ring\"}","config.yaml":"apiVersion: v1\nkind: Config\nmetadata:\n  name: ascend-config"}'
  tasks:
  - name: "task-1"
    replicas: 1
    template:
      spec:
        containers:
        - name: test-container
          image: nginx:latest
          command:
          - sleep
          - "3600"
        restartPolicy: Never
