apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: test-ringsconfigmap-job
  namespace: default
spec:
  minAvailable: 1
  schedulerName: volcano
  plugins:
    ringsconfigmap: {}
  tasks:
  - name: "task-1"
    replicas: 1
    template:
      spec:
        containers:
        - name: test-container
          image: nginx:latest
          command:
          - sleep
          - "3600"
        restartPolicy: Never
