FROM alpine:latest

COPY vc-controller-manager /vc-controller-manager

RUN adduser -h /home/hwMindX -u 9000 -D -s /sbin/nologin hwMindX && \
    sed '1c root:x:0:0:root:/root:/sbin/nologin' /etc/passwd && \
    chown -R hwMindX:hwMindX vc-controller-manager && \
    chmod 750 /home/hwMindX && \
    chmod 500 vc-controller-manager
USER hwMindX