/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	schedulingv1beta1 "volcano.sh/apis/pkg/apis/scheduling/v1beta1"
	applyconfigurationschedulingv1beta1 "volcano.sh/apis/pkg/client/applyconfiguration/scheduling/v1beta1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// NamespaceQueuesGetter has a method to return a NamespaceQueueInterface.
// A group's client should implement this interface.
type NamespaceQueuesGetter interface {
	NamespaceQueues(namespace string) NamespaceQueueInterface
}

// NamespaceQueueInterface has methods to work with NamespaceQueue resources.
type NamespaceQueueInterface interface {
	Create(ctx context.Context, namespaceQueue *schedulingv1beta1.NamespaceQueue, opts v1.CreateOptions) (*schedulingv1beta1.NamespaceQueue, error)
	Update(ctx context.Context, namespaceQueue *schedulingv1beta1.NamespaceQueue, opts v1.UpdateOptions) (*schedulingv1beta1.NamespaceQueue, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, namespaceQueue *schedulingv1beta1.NamespaceQueue, opts v1.UpdateOptions) (*schedulingv1beta1.NamespaceQueue, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*schedulingv1beta1.NamespaceQueue, error)
	List(ctx context.Context, opts v1.ListOptions) (*schedulingv1beta1.NamespaceQueueList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *schedulingv1beta1.NamespaceQueue, err error)
	Apply(ctx context.Context, namespaceQueue *applyconfigurationschedulingv1beta1.NamespaceQueueApplyConfiguration, opts v1.ApplyOptions) (result *schedulingv1beta1.NamespaceQueue, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, namespaceQueue *applyconfigurationschedulingv1beta1.NamespaceQueueApplyConfiguration, opts v1.ApplyOptions) (result *schedulingv1beta1.NamespaceQueue, err error)
	NamespaceQueueExpansion
}

// namespaceQueues implements NamespaceQueueInterface
type namespaceQueues struct {
	*gentype.ClientWithListAndApply[*schedulingv1beta1.NamespaceQueue, *schedulingv1beta1.NamespaceQueueList, *applyconfigurationschedulingv1beta1.NamespaceQueueApplyConfiguration]
}

// newNamespaceQueues returns a NamespaceQueues
func newNamespaceQueues(c *SchedulingV1beta1Client, namespace string) *namespaceQueues {
	return &namespaceQueues{
		gentype.NewClientWithListAndApply[*schedulingv1beta1.NamespaceQueue, *schedulingv1beta1.NamespaceQueueList, *applyconfigurationschedulingv1beta1.NamespaceQueueApplyConfiguration](
			"namespacequeues",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *schedulingv1beta1.NamespaceQueue { return &schedulingv1beta1.NamespaceQueue{} },
			func() *schedulingv1beta1.NamespaceQueueList { return &schedulingv1beta1.NamespaceQueueList{} },
		),
	}
}
