/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DataSourceStatusApplyConfiguration represents a declarative configuration of the DataSourceStatus type for use
// with apply.
type DataSourceStatusApplyConfiguration struct {
	ClaimRefs   []v1.ObjectReference                 `json:"claimRefs,omitempty"`
	BoundClaims *int32                               `json:"boundClaims,omitempty"`
	Conditions  []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// DataSourceStatusApplyConfiguration constructs a declarative configuration of the DataSourceStatus type for use with
// apply.
func DataSourceStatus() *DataSourceStatusApplyConfiguration {
	return &DataSourceStatusApplyConfiguration{}
}

// WithClaimRefs adds the given value to the ClaimRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ClaimRefs field.
func (b *DataSourceStatusApplyConfiguration) WithClaimRefs(values ...v1.ObjectReference) *DataSourceStatusApplyConfiguration {
	for i := range values {
		b.ClaimRefs = append(b.ClaimRefs, values[i])
	}
	return b
}

// WithBoundClaims sets the BoundClaims field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BoundClaims field is set to the value of the last call.
func (b *DataSourceStatusApplyConfiguration) WithBoundClaims(value int32) *DataSourceStatusApplyConfiguration {
	b.BoundClaims = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DataSourceStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *DataSourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
