/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DataSourceLocalityApplyConfiguration represents a declarative configuration of the DataSourceLocality type for use
// with apply.
//
// DataSourceLocality specifies the cached location information of the data source.
type DataSourceLocalityApplyConfiguration struct {
	// ClusterNames is a list of cluster names where the cached data source information indicates availability.
	// This provides a simple and direct way to specify cached data source location
	// without interfering with user-defined ResourceBinding cluster affinity.
	ClusterNames []string `json:"clusterNames,omitempty"`
}

// DataSourceLocalityApplyConfiguration constructs a declarative configuration of the DataSourceLocality type for use with
// apply.
func DataSourceLocality() *DataSourceLocalityApplyConfiguration {
	return &DataSourceLocalityApplyConfiguration{}
}

// WithClusterNames adds the given value to the ClusterNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ClusterNames field.
func (b *DataSourceLocalityApplyConfiguration) WithClusterNames(values ...string) *DataSourceLocalityApplyConfiguration {
	for i := range values {
		b.ClusterNames = append(b.ClusterNames, values[i])
	}
	return b
}
