
# If tag not explicitly set in users default to the git sha.
TAG=v0.3
GitSHA=a2a6ee8904f69f2bfc4aa5992f84a59c26b4158f
Date=`date "+%Y-%m-%d %H:%M:%S"`
LD_FLAGS=" \
    -X '${REPO_PATH}/pkg/version.GitSHA=${GitSHA}' \
    -X '${REPO_PATH}/pkg/version.Built=${Date}'   \
    -X '${REPO_PATH}/pkg/version.Version=${RELEASE_VER}'"

