/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// PodGroupAntiAffinityApplyConfiguration represents a declarative configuration of the PodGroupAntiAffinity type for use
// with apply.
//
// PodGroupAntiAffinity defines required/preferred anti-affinity against other PodGroups.
type PodGroupAntiAffinityApplyConfiguration struct {
	Required  []PodGroupAffinityTermApplyConfiguration `json:"required,omitempty"`
	Preferred []PodGroupAffinityTermApplyConfiguration `json:"preferred,omitempty"`
}

// PodGroupAntiAffinityApplyConfiguration constructs a declarative configuration of the PodGroupAntiAffinity type for use with
// apply.
func PodGroupAntiAffinity() *PodGroupAntiAffinityApplyConfiguration {
	return &PodGroupAntiAffinityApplyConfiguration{}
}

// WithRequired adds the given value to the Required field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Required field.
func (b *PodGroupAntiAffinityApplyConfiguration) WithRequired(values ...*PodGroupAffinityTermApplyConfiguration) *PodGroupAntiAffinityApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRequired")
		}
		b.Required = append(b.Required, *values[i])
	}
	return b
}

// WithPreferred adds the given value to the Preferred field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Preferred field.
func (b *PodGroupAntiAffinityApplyConfiguration) WithPreferred(values ...*PodGroupAffinityTermApplyConfiguration) *PodGroupAntiAffinityApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPreferred")
		}
		b.Preferred = append(b.Preferred, *values[i])
	}
	return b
}
