/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodGroupAffinityTermApplyConfiguration represents a declarative configuration of the PodGroupAffinityTerm type for use
// with apply.
//
// PodGroupAffinityTerm selects matching PodGroups and the topology tier for HyperNode comparison.
type PodGroupAffinityTermApplyConfiguration struct {
	Weight            *int32                              `json:"weight,omitempty"`
	PodGroupSelector  *v1.LabelSelectorApplyConfiguration `json:"podGroupSelector,omitempty"`
	NamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
	TopologyTierName  *string                             `json:"topologyTierName,omitempty"`
	TopologyTier      *int32                              `json:"topologyTier,omitempty"`
}

// PodGroupAffinityTermApplyConfiguration constructs a declarative configuration of the PodGroupAffinityTerm type for use with
// apply.
func PodGroupAffinityTerm() *PodGroupAffinityTermApplyConfiguration {
	return &PodGroupAffinityTermApplyConfiguration{}
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *PodGroupAffinityTermApplyConfiguration) WithWeight(value int32) *PodGroupAffinityTermApplyConfiguration {
	b.Weight = &value
	return b
}

// WithPodGroupSelector sets the PodGroupSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroupSelector field is set to the value of the last call.
func (b *PodGroupAffinityTermApplyConfiguration) WithPodGroupSelector(value *v1.LabelSelectorApplyConfiguration) *PodGroupAffinityTermApplyConfiguration {
	b.PodGroupSelector = value
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *PodGroupAffinityTermApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *PodGroupAffinityTermApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

// WithTopologyTierName sets the TopologyTierName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyTierName field is set to the value of the last call.
func (b *PodGroupAffinityTermApplyConfiguration) WithTopologyTierName(value string) *PodGroupAffinityTermApplyConfiguration {
	b.TopologyTierName = &value
	return b
}

// WithTopologyTier sets the TopologyTier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyTier field is set to the value of the last call.
func (b *PodGroupAffinityTermApplyConfiguration) WithTopologyTier(value int32) *PodGroupAffinityTermApplyConfiguration {
	b.TopologyTier = &value
	return b
}
