/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// ReservationApplyConfiguration represents a declarative configuration of the Reservation type for use
// with apply.
//
// Reservation represents current condition about resource reservation
type ReservationApplyConfiguration struct {
	// Nodes are Locked nodes for queue
	Nodes []string `json:"nodes,omitempty"`
	// Resource is a list of total idle resource in locked nodes.
	Resource *v1.ResourceList `json:"resource,omitempty"`
}

// ReservationApplyConfiguration constructs a declarative configuration of the Reservation type for use with
// apply.
func Reservation() *ReservationApplyConfiguration {
	return &ReservationApplyConfiguration{}
}

// WithNodes adds the given value to the Nodes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Nodes field.
func (b *ReservationApplyConfiguration) WithNodes(values ...string) *ReservationApplyConfiguration {
	for i := range values {
		b.Nodes = append(b.Nodes, values[i])
	}
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *ReservationApplyConfiguration) WithResource(value v1.ResourceList) *ReservationApplyConfiguration {
	b.Resource = &value
	return b
}
