/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// TopologyAffinitySpecApplyConfiguration represents a declarative configuration of the TopologyAffinitySpec type for use
// with apply.
//
// TopologyAffinitySpec holds group topology affinity and anti-affinity rules.
type TopologyAffinitySpecApplyConfiguration struct {
	PodGroupAntiAffinity *PodGroupAntiAffinityApplyConfiguration `json:"podGroupAntiAffinity,omitempty"`
	SubGroupAffinity     *SubGroupAffinityApplyConfiguration     `json:"subGroupAffinity,omitempty"`
	SubGroupAntiAffinity *SubGroupAntiAffinityApplyConfiguration `json:"subGroupAntiAffinity,omitempty"`
}

// TopologyAffinitySpecApplyConfiguration constructs a declarative configuration of the TopologyAffinitySpec type for use with
// apply.
func TopologyAffinitySpec() *TopologyAffinitySpecApplyConfiguration {
	return &TopologyAffinitySpecApplyConfiguration{}
}

// WithPodGroupAntiAffinity sets the PodGroupAntiAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodGroupAntiAffinity field is set to the value of the last call.
func (b *TopologyAffinitySpecApplyConfiguration) WithPodGroupAntiAffinity(value *PodGroupAntiAffinityApplyConfiguration) *TopologyAffinitySpecApplyConfiguration {
	b.PodGroupAntiAffinity = value
	return b
}

// WithSubGroupAffinity sets the SubGroupAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubGroupAffinity field is set to the value of the last call.
func (b *TopologyAffinitySpecApplyConfiguration) WithSubGroupAffinity(value *SubGroupAffinityApplyConfiguration) *TopologyAffinitySpecApplyConfiguration {
	b.SubGroupAffinity = value
	return b
}

// WithSubGroupAntiAffinity sets the SubGroupAntiAffinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubGroupAntiAffinity field is set to the value of the last call.
func (b *TopologyAffinitySpecApplyConfiguration) WithSubGroupAntiAffinity(value *SubGroupAntiAffinityApplyConfiguration) *TopologyAffinitySpecApplyConfiguration {
	b.SubGroupAntiAffinity = value
	return b
}
