/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ColocationConfigurationSpecApplyConfiguration represents a declarative configuration of the ColocationConfigurationSpec type for use
// with apply.
type ColocationConfigurationSpecApplyConfiguration struct {
	Selector                        *v1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
	ConfigurationApplyConfiguration `json:",inline"`
}

// ColocationConfigurationSpecApplyConfiguration constructs a declarative configuration of the ColocationConfigurationSpec type for use with
// apply.
func ColocationConfigurationSpec() *ColocationConfigurationSpecApplyConfiguration {
	return &ColocationConfigurationSpecApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *ColocationConfigurationSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *ColocationConfigurationSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithMemoryQos sets the MemoryQos field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemoryQos field is set to the value of the last call.
func (b *ColocationConfigurationSpecApplyConfiguration) WithMemoryQos(value *MemoryQosApplyConfiguration) *ColocationConfigurationSpecApplyConfiguration {
	b.ConfigurationApplyConfiguration.MemoryQos = value
	return b
}
