/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ColocationConfigurationStatusApplyConfiguration represents a declarative configuration of the ColocationConfigurationStatus type for use
// with apply.
//
// ColocationConfigurationStatus defines the observed state of ColocationConfiguration.
type ColocationConfigurationStatusApplyConfiguration struct {
	// conditions represent the current state of the ColocationConfiguration resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ColocationConfigurationStatusApplyConfiguration constructs a declarative configuration of the ColocationConfigurationStatus type for use with
// apply.
func ColocationConfigurationStatus() *ColocationConfigurationStatusApplyConfiguration {
	return &ColocationConfigurationStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ColocationConfigurationStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ColocationConfigurationStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
