/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MemoryQosApplyConfiguration represents a declarative configuration of the MemoryQos type for use
// with apply.
type MemoryQosApplyConfiguration struct {
	HighRatio *int `json:"highRatio,omitempty"`
	LowRatio  *int `json:"lowRatio,omitempty"`
	MinRatio  *int `json:"minRatio,omitempty"`
}

// MemoryQosApplyConfiguration constructs a declarative configuration of the MemoryQos type for use with
// apply.
func MemoryQos() *MemoryQosApplyConfiguration {
	return &MemoryQosApplyConfiguration{}
}

// WithHighRatio sets the HighRatio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HighRatio field is set to the value of the last call.
func (b *MemoryQosApplyConfiguration) WithHighRatio(value int) *MemoryQosApplyConfiguration {
	b.HighRatio = &value
	return b
}

// WithLowRatio sets the LowRatio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LowRatio field is set to the value of the last call.
func (b *MemoryQosApplyConfiguration) WithLowRatio(value int) *MemoryQosApplyConfiguration {
	b.LowRatio = &value
	return b
}

// WithMinRatio sets the MinRatio field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinRatio field is set to the value of the last call.
func (b *MemoryQosApplyConfiguration) WithMinRatio(value int) *MemoryQosApplyConfiguration {
	b.MinRatio = &value
	return b
}
