/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	nodeinfov1alpha1 "volcano.sh/apis/pkg/apis/nodeinfo/v1alpha1"
)

// NumatopologyLister helps list Numatopologies.
// All objects returned here must be treated as read-only.
type NumatopologyLister interface {
	// List lists all Numatopologies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*nodeinfov1alpha1.Numatopology, err error)
	// Get retrieves the Numatopology from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*nodeinfov1alpha1.Numatopology, error)
	NumatopologyListerExpansion
}

// numatopologyLister implements the NumatopologyLister interface.
type numatopologyLister struct {
	listers.ResourceIndexer[*nodeinfov1alpha1.Numatopology]
}

// NewNumatopologyLister returns a new NumatopologyLister.
func NewNumatopologyLister(indexer cache.Indexer) NumatopologyLister {
	return &numatopologyLister{listers.New[*nodeinfov1alpha1.Numatopology](indexer, nodeinfov1alpha1.Resource("numatopology"))}
}
