# permissions for namespace users to manage NamespaceQueues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacequeue-editor-role
  {{- if or .Values.custom.aggregationRule_labels .Values.custom.common_labels }}
  labels:
    {{- if .Values.custom.aggregationRule_labels }}
      {{- toYaml .Values.custom.aggregationRule_labels | nindent 4 }}
    {{- end }}
    {{- if .Values.custom.common_labels }}
      {{- toYaml .Values.custom.common_labels | nindent 4 }}
    {{- end }}
  {{- end }}
rules:
  - apiGroups: ["scheduling.volcano.sh"]
    resources: ["namespacequeues"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
