/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GPUInfoApplyConfiguration represents a declarative configuration of the GPUInfo type for use
// with apply.
//
// GPUInfo contains the NUMA topology information for a single GPU device,
// including its NUMA node affinity, PCI bus ID, and device model.
type GPUInfoApplyConfiguration struct {
	// NUMANodeID is the NUMA node to which this GPU is attached.
	NUMANodeID *int `json:"numa,omitempty"`
	// BusID is the PCI Bus-Device-Function address (e.g. "0000:3b:00.0").
	BusID *string `json:"busID,omitempty"`
	// DeviceModel is the human-readable GPU model name or PCI vendor:device ID.
	DeviceModel *string `json:"deviceModel,omitempty"`
}

// GPUInfoApplyConfiguration constructs a declarative configuration of the GPUInfo type for use with
// apply.
func GPUInfo() *GPUInfoApplyConfiguration {
	return &GPUInfoApplyConfiguration{}
}

// WithNUMANodeID sets the NUMANodeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NUMANodeID field is set to the value of the last call.
func (b *GPUInfoApplyConfiguration) WithNUMANodeID(value int) *GPUInfoApplyConfiguration {
	b.NUMANodeID = &value
	return b
}

// WithBusID sets the BusID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BusID field is set to the value of the last call.
func (b *GPUInfoApplyConfiguration) WithBusID(value string) *GPUInfoApplyConfiguration {
	b.BusID = &value
	return b
}

// WithDeviceModel sets the DeviceModel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeviceModel field is set to the value of the last call.
func (b *GPUInfoApplyConfiguration) WithDeviceModel(value string) *GPUInfoApplyConfiguration {
	b.DeviceModel = &value
	return b
}
