name: Enhancement
description: Suggest an idea for volcano
labels: kind/feature
body:
  - type: textarea
    attributes:
      label: What is the problem you're trying to solve
      description: |
        A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you'd like to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: |
        Add any other context about the feature request here.

  - type: checkboxes
    attributes:
      label: Documentation Updates
      description: |
        Please confirm if documentation updates are needed for this enhancement.
      options:
        - label: This feature requires design or user documentation changes.
          required: false
        - label: If documentation changes are required, I will ensure the relevant documents are updated and published to the Volcano official website (https://volcano.sh) via the [volcano-sh/website](https://github.com/volcano-sh/website) repository.
          required: false
