/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MemberSelectorApplyConfiguration represents a declarative configuration of the MemberSelector type for use
// with apply.
type MemberSelectorApplyConfiguration struct {
	ExactMatch *ExactMatchApplyConfiguration       `json:"exactMatch,omitempty"`
	RegexMatch *RegexMatchApplyConfiguration       `json:"regexMatch,omitempty"`
	LabelMatch *v1.LabelSelectorApplyConfiguration `json:"labelMatch,omitempty"`
}

// MemberSelectorApplyConfiguration constructs a declarative configuration of the MemberSelector type for use with
// apply.
func MemberSelector() *MemberSelectorApplyConfiguration {
	return &MemberSelectorApplyConfiguration{}
}

// WithExactMatch sets the ExactMatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExactMatch field is set to the value of the last call.
func (b *MemberSelectorApplyConfiguration) WithExactMatch(value *ExactMatchApplyConfiguration) *MemberSelectorApplyConfiguration {
	b.ExactMatch = value
	return b
}

// WithRegexMatch sets the RegexMatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RegexMatch field is set to the value of the last call.
func (b *MemberSelectorApplyConfiguration) WithRegexMatch(value *RegexMatchApplyConfiguration) *MemberSelectorApplyConfiguration {
	b.RegexMatch = value
	return b
}

// WithLabelMatch sets the LabelMatch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelMatch field is set to the value of the last call.
func (b *MemberSelectorApplyConfiguration) WithLabelMatch(value *v1.LabelSelectorApplyConfiguration) *MemberSelectorApplyConfiguration {
	b.LabelMatch = value
	return b
}
