/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	busv1alpha1 "volcano.sh/apis/pkg/apis/bus/v1alpha1"
	applyconfigurationbusv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/bus/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// CommandsGetter has a method to return a CommandInterface.
// A group's client should implement this interface.
type CommandsGetter interface {
	Commands(namespace string) CommandInterface
}

// CommandInterface has methods to work with Command resources.
type CommandInterface interface {
	Create(ctx context.Context, command *busv1alpha1.Command, opts v1.CreateOptions) (*busv1alpha1.Command, error)
	Update(ctx context.Context, command *busv1alpha1.Command, opts v1.UpdateOptions) (*busv1alpha1.Command, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*busv1alpha1.Command, error)
	List(ctx context.Context, opts v1.ListOptions) (*busv1alpha1.CommandList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *busv1alpha1.Command, err error)
	Apply(ctx context.Context, command *applyconfigurationbusv1alpha1.CommandApplyConfiguration, opts v1.ApplyOptions) (result *busv1alpha1.Command, err error)
	CommandExpansion
}

// commands implements CommandInterface
type commands struct {
	*gentype.ClientWithListAndApply[*busv1alpha1.Command, *busv1alpha1.CommandList, *applyconfigurationbusv1alpha1.CommandApplyConfiguration]
}

// newCommands returns a Commands
func newCommands(c *BusV1alpha1Client, namespace string) *commands {
	return &commands{
		gentype.NewClientWithListAndApply[*busv1alpha1.Command, *busv1alpha1.CommandList, *applyconfigurationbusv1alpha1.CommandApplyConfiguration](
			"commands",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *busv1alpha1.Command { return &busv1alpha1.Command{} },
			func() *busv1alpha1.CommandList { return &busv1alpha1.CommandList{} },
		),
	}
}
