// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Queue).DeepCopyInto(out.(*Queue))
			return nil
		}, InType: reflect.TypeOf(&Queue{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueJob).DeepCopyInto(out.(*QueueJob))
			return nil
		}, InType: reflect.TypeOf(&QueueJob{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueJobList).DeepCopyInto(out.(*QueueJobList))
			return nil
		}, InType: reflect.TypeOf(&QueueJobList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueJobResource).DeepCopyInto(out.(*QueueJobResource))
			return nil
		}, InType: reflect.TypeOf(&QueueJobResource{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueJobResourceList).DeepCopyInto(out.(*QueueJobResourceList))
			return nil
		}, InType: reflect.TypeOf(&QueueJobResourceList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueJobService).DeepCopyInto(out.(*QueueJobService))
			return nil
		}, InType: reflect.TypeOf(&QueueJobService{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueJobSpec).DeepCopyInto(out.(*QueueJobSpec))
			return nil
		}, InType: reflect.TypeOf(&QueueJobSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueJobStatus).DeepCopyInto(out.(*QueueJobStatus))
			return nil
		}, InType: reflect.TypeOf(&QueueJobStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueList).DeepCopyInto(out.(*QueueList))
			return nil
		}, InType: reflect.TypeOf(&QueueList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueSpec).DeepCopyInto(out.(*QueueSpec))
			return nil
		}, InType: reflect.TypeOf(&QueueSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*QueueStatus).DeepCopyInto(out.(*QueueStatus))
			return nil
		}, InType: reflect.TypeOf(&QueueStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ResourceList).DeepCopyInto(out.(*ResourceList))
			return nil
		}, InType: reflect.TypeOf(&ResourceList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ResourceUsageStatus).DeepCopyInto(out.(*ResourceUsageStatus))
			return nil
		}, InType: reflect.TypeOf(&ResourceUsageStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*TaskSet).DeepCopyInto(out.(*TaskSet))
			return nil
		}, InType: reflect.TypeOf(&TaskSet{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*TaskSetList).DeepCopyInto(out.(*TaskSetList))
			return nil
		}, InType: reflect.TypeOf(&TaskSetList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*TaskSetSpec).DeepCopyInto(out.(*TaskSetSpec))
			return nil
		}, InType: reflect.TypeOf(&TaskSetSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*TaskSetStatus).DeepCopyInto(out.(*TaskSetStatus))
			return nil
		}, InType: reflect.TypeOf(&TaskSetStatus{})},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Queue) DeepCopyInto(out *Queue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Queue.
func (in *Queue) DeepCopy() *Queue {
	if in == nil {
		return nil
	}
	out := new(Queue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Queue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueJob) DeepCopyInto(out *QueueJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueJob.
func (in *QueueJob) DeepCopy() *QueueJob {
	if in == nil {
		return nil
	}
	out := new(QueueJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueJobList) DeepCopyInto(out *QueueJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueueJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueJobList.
func (in *QueueJobList) DeepCopy() *QueueJobList {
	if in == nil {
		return nil
	}
	out := new(QueueJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueJobResource) DeepCopyInto(out *QueueJobResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Template.DeepCopyInto(&out.Template)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueJobResource.
func (in *QueueJobResource) DeepCopy() *QueueJobResource {
	if in == nil {
		return nil
	}
	out := new(QueueJobResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueJobResourceList) DeepCopyInto(out *QueueJobResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QueueJobResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueJobResourceList.
func (in *QueueJobResourceList) DeepCopy() *QueueJobResourceList {
	if in == nil {
		return nil
	}
	out := new(QueueJobResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueJobService) DeepCopyInto(out *QueueJobService) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueJobService.
func (in *QueueJobService) DeepCopy() *QueueJobService {
	if in == nil {
		return nil
	}
	out := new(QueueJobService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueJobSpec) DeepCopyInto(out *QueueJobSpec) {
	*out = *in
	in.Service.DeepCopyInto(&out.Service)
	in.AggrResources.DeepCopyInto(&out.AggrResources)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueJobSpec.
func (in *QueueJobSpec) DeepCopy() *QueueJobSpec {
	if in == nil {
		return nil
	}
	out := new(QueueJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueJobStatus) DeepCopyInto(out *QueueJobStatus) {
	*out = *in
	in.ResourceUsage.DeepCopyInto(&out.ResourceUsage)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueJobStatus.
func (in *QueueJobStatus) DeepCopy() *QueueJobStatus {
	if in == nil {
		return nil
	}
	out := new(QueueJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueList) DeepCopyInto(out *QueueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Queue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueList.
func (in *QueueList) DeepCopy() *QueueList {
	if in == nil {
		return nil
	}
	out := new(QueueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QueueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueSpec) DeepCopyInto(out *QueueSpec) {
	*out = *in
	in.Request.DeepCopyInto(&out.Request)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueSpec.
func (in *QueueSpec) DeepCopy() *QueueSpec {
	if in == nil {
		return nil
	}
	out := new(QueueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueStatus) DeepCopyInto(out *QueueStatus) {
	*out = *in
	in.Deserved.DeepCopyInto(&out.Deserved)
	in.Allocated.DeepCopyInto(&out.Allocated)
	in.Used.DeepCopyInto(&out.Used)
	in.Preempting.DeepCopyInto(&out.Preempting)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueStatus.
func (in *QueueStatus) DeepCopy() *QueueStatus {
	if in == nil {
		return nil
	}
	out := new(QueueStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceList) DeepCopyInto(out *ResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[ResourceName]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceList.
func (in *ResourceList) DeepCopy() *ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceUsageStatus) DeepCopyInto(out *ResourceUsageStatus) {
	*out = *in
	in.Deserved.DeepCopyInto(&out.Deserved)
	in.Allocated.DeepCopyInto(&out.Allocated)
	in.Used.DeepCopyInto(&out.Used)
	in.Preempting.DeepCopyInto(&out.Preempting)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceUsageStatus.
func (in *ResourceUsageStatus) DeepCopy() *ResourceUsageStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceUsageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSet) DeepCopyInto(out *TaskSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSet.
func (in *TaskSet) DeepCopy() *TaskSet {
	if in == nil {
		return nil
	}
	out := new(TaskSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSetList) DeepCopyInto(out *TaskSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TaskSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSetList.
func (in *TaskSetList) DeepCopy() *TaskSetList {
	if in == nil {
		return nil
	}
	out := new(TaskSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TaskSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSetSpec) DeepCopyInto(out *TaskSetSpec) {
	*out = *in
	in.ResourceUnit.DeepCopyInto(&out.ResourceUnit)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSetSpec.
func (in *TaskSetSpec) DeepCopy() *TaskSetSpec {
	if in == nil {
		return nil
	}
	out := new(TaskSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TaskSetStatus) DeepCopyInto(out *TaskSetStatus) {
	*out = *in
	in.Allocated.DeepCopyInto(&out.Allocated)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TaskSetStatus.
func (in *TaskSetStatus) DeepCopy() *TaskSetStatus {
	if in == nil {
		return nil
	}
	out := new(TaskSetStatus)
	in.DeepCopyInto(out)
	return out
}
