# Copyright 2025 The Volcano Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM golang:1.25.0

ARG TARGETARCH
ARG COMPONENT
ENV COMPONENT=${COMPONENT}
ENV VOLCANO_HOME=/go/src/volcano.sh/volcano

RUN apt-get update && \
    apt-get install -y ca-certificates openssl curl dumb-init less && \
    rm -rf /var/lib/apt/lists/*

WORKDIR ${VOLCANO_HOME}
COPY go.mod go.sum ./
# Copy staging directory before go mod download since go.mod has replace directive
COPY staging/ ./staging/
RUN go mod download

COPY pkg/ ./pkg/
COPY third_party/ ./third_party/
COPY cmd/ ./cmd/
COPY hack/tilt/entrypoint.sh ${VOLCANO_HOME}/entrypoint.sh

RUN chmod +x ${VOLCANO_HOME}/entrypoint.sh
RUN chown -R 1000:1000 ${VOLCANO_HOME}
RUN useradd -u 1000 -m developer
USER developer

RUN GOOS=linux GOARCH=${TARGETARCH} go build -o ${VOLCANO_HOME}/vc-${COMPONENT} ./cmd/${COMPONENT}

ENTRYPOINT ["/usr/bin/dumb-init", "-c", "--", "/go/src/volcano.sh/volcano/entrypoint.sh"]
