/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HyperJobStatusApplyConfiguration represents a declarative configuration of the HyperJobStatus type for use
// with apply.
type HyperJobStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ReplicatedJobsStatus tracks the status of each replicated job.
	ReplicatedJobsStatus []ReplicatedJobStatusApplyConfiguration `json:"replicatedJobsStatus,omitempty"`
	// SplitCount represents the total number of volcano jobs this hyperjob is split into by the controller.
	SplitCount *int32 `json:"splitCount,omitempty"`
	// The generation observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// HyperJobStatusApplyConfiguration constructs a declarative configuration of the HyperJobStatus type for use with
// apply.
func HyperJobStatus() *HyperJobStatusApplyConfiguration {
	return &HyperJobStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *HyperJobStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *HyperJobStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithReplicatedJobsStatus adds the given value to the ReplicatedJobsStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReplicatedJobsStatus field.
func (b *HyperJobStatusApplyConfiguration) WithReplicatedJobsStatus(values ...*ReplicatedJobStatusApplyConfiguration) *HyperJobStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReplicatedJobsStatus")
		}
		b.ReplicatedJobsStatus = append(b.ReplicatedJobsStatus, *values[i])
	}
	return b
}

// WithSplitCount sets the SplitCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SplitCount field is set to the value of the last call.
func (b *HyperJobStatusApplyConfiguration) WithSplitCount(value int32) *HyperJobStatusApplyConfiguration {
	b.SplitCount = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *HyperJobStatusApplyConfiguration) WithObservedGeneration(value int64) *HyperJobStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
