/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NodeShardSpecApplyConfiguration represents a declarative configuration of the NodeShardSpec type for use
// with apply.
//
// NodeShardSpec represents the template of a NodeShard.
type NodeShardSpecApplyConfiguration struct {
	// NodesDesired defines the list of nodes desired to be included in this NodeShard.
	NodesDesired []string `json:"nodesDesired,omitempty"`
}

// NodeShardSpecApplyConfiguration constructs a declarative configuration of the NodeShardSpec type for use with
// apply.
func NodeShardSpec() *NodeShardSpecApplyConfiguration {
	return &NodeShardSpecApplyConfiguration{}
}

// WithNodesDesired adds the given value to the NodesDesired field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NodesDesired field.
func (b *NodeShardSpecApplyConfiguration) WithNodesDesired(values ...string) *NodeShardSpecApplyConfiguration {
	for i := range values {
		b.NodesDesired = append(b.NodesDesired, values[i])
	}
	return b
}
