/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	datadependencyv1alpha1 "volcano.sh/apis/pkg/apis/datadependency/v1alpha1"
)

// DataSourceLister helps list DataSources.
// All objects returned here must be treated as read-only.
type DataSourceLister interface {
	// List lists all DataSources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*datadependencyv1alpha1.DataSource, err error)
	// Get retrieves the DataSource from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*datadependencyv1alpha1.DataSource, error)
	DataSourceListerExpansion
}

// dataSourceLister implements the DataSourceLister interface.
type dataSourceLister struct {
	listers.ResourceIndexer[*datadependencyv1alpha1.DataSource]
}

// NewDataSourceLister returns a new DataSourceLister.
func NewDataSourceLister(indexer cache.Indexer) DataSourceLister {
	return &dataSourceLister{listers.New[*datadependencyv1alpha1.DataSource](indexer, datadependencyv1alpha1.Resource("datasource"))}
}
