/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	shardv1alpha1 "volcano.sh/apis/pkg/apis/shard/v1alpha1"
	applyconfigurationshardv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/shard/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// NodeShardsGetter has a method to return a NodeShardInterface.
// A group's client should implement this interface.
type NodeShardsGetter interface {
	NodeShards() NodeShardInterface
}

// NodeShardInterface has methods to work with NodeShard resources.
type NodeShardInterface interface {
	Create(ctx context.Context, nodeShard *shardv1alpha1.NodeShard, opts v1.CreateOptions) (*shardv1alpha1.NodeShard, error)
	Update(ctx context.Context, nodeShard *shardv1alpha1.NodeShard, opts v1.UpdateOptions) (*shardv1alpha1.NodeShard, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, nodeShard *shardv1alpha1.NodeShard, opts v1.UpdateOptions) (*shardv1alpha1.NodeShard, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*shardv1alpha1.NodeShard, error)
	List(ctx context.Context, opts v1.ListOptions) (*shardv1alpha1.NodeShardList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *shardv1alpha1.NodeShard, err error)
	Apply(ctx context.Context, nodeShard *applyconfigurationshardv1alpha1.NodeShardApplyConfiguration, opts v1.ApplyOptions) (result *shardv1alpha1.NodeShard, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, nodeShard *applyconfigurationshardv1alpha1.NodeShardApplyConfiguration, opts v1.ApplyOptions) (result *shardv1alpha1.NodeShard, err error)
	NodeShardExpansion
}

// nodeShards implements NodeShardInterface
type nodeShards struct {
	*gentype.ClientWithListAndApply[*shardv1alpha1.NodeShard, *shardv1alpha1.NodeShardList, *applyconfigurationshardv1alpha1.NodeShardApplyConfiguration]
}

// newNodeShards returns a NodeShards
func newNodeShards(c *ShardV1alpha1Client) *nodeShards {
	return &nodeShards{
		gentype.NewClientWithListAndApply[*shardv1alpha1.NodeShard, *shardv1alpha1.NodeShardList, *applyconfigurationshardv1alpha1.NodeShardApplyConfiguration](
			"nodeshards",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *shardv1alpha1.NodeShard { return &shardv1alpha1.NodeShard{} },
			func() *shardv1alpha1.NodeShardList { return &shardv1alpha1.NodeShardList{} },
		),
	}
}
