/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// JobTemplateStatusApplyConfiguration represents a declarative configuration of the JobTemplateStatus type for use
// with apply.
//
// JobTemplateStatus defines the observed state of JobTemplate
type JobTemplateStatusApplyConfiguration struct {
	// JobDependsOnList is the list of jobs that this job depends on
	JobDependsOnList []string `json:"jobDependsOnList,omitempty"`
}

// JobTemplateStatusApplyConfiguration constructs a declarative configuration of the JobTemplateStatus type for use with
// apply.
func JobTemplateStatus() *JobTemplateStatusApplyConfiguration {
	return &JobTemplateStatusApplyConfiguration{}
}

// WithJobDependsOnList adds the given value to the JobDependsOnList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the JobDependsOnList field.
func (b *JobTemplateStatusApplyConfiguration) WithJobDependsOnList(values ...string) *JobTemplateStatusApplyConfiguration {
	for i := range values {
		b.JobDependsOnList = append(b.JobDependsOnList, values[i])
	}
	return b
}
