/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	batchv1alpha1 "volcano.sh/apis/pkg/apis/batch/v1alpha1"
	applyconfigurationbatchv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/batch/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// CronJobsGetter has a method to return a CronJobInterface.
// A group's client should implement this interface.
type CronJobsGetter interface {
	CronJobs(namespace string) CronJobInterface
}

// CronJobInterface has methods to work with CronJob resources.
type CronJobInterface interface {
	Create(ctx context.Context, cronJob *batchv1alpha1.CronJob, opts v1.CreateOptions) (*batchv1alpha1.CronJob, error)
	Update(ctx context.Context, cronJob *batchv1alpha1.CronJob, opts v1.UpdateOptions) (*batchv1alpha1.CronJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cronJob *batchv1alpha1.CronJob, opts v1.UpdateOptions) (*batchv1alpha1.CronJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*batchv1alpha1.CronJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*batchv1alpha1.CronJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *batchv1alpha1.CronJob, err error)
	Apply(ctx context.Context, cronJob *applyconfigurationbatchv1alpha1.CronJobApplyConfiguration, opts v1.ApplyOptions) (result *batchv1alpha1.CronJob, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, cronJob *applyconfigurationbatchv1alpha1.CronJobApplyConfiguration, opts v1.ApplyOptions) (result *batchv1alpha1.CronJob, err error)
	CronJobExpansion
}

// cronJobs implements CronJobInterface
type cronJobs struct {
	*gentype.ClientWithListAndApply[*batchv1alpha1.CronJob, *batchv1alpha1.CronJobList, *applyconfigurationbatchv1alpha1.CronJobApplyConfiguration]
}

// newCronJobs returns a CronJobs
func newCronJobs(c *BatchV1alpha1Client, namespace string) *cronJobs {
	return &cronJobs{
		gentype.NewClientWithListAndApply[*batchv1alpha1.CronJob, *batchv1alpha1.CronJobList, *applyconfigurationbatchv1alpha1.CronJobApplyConfiguration](
			"cronjobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *batchv1alpha1.CronJob { return &batchv1alpha1.CronJob{} },
			func() *batchv1alpha1.CronJobList { return &batchv1alpha1.CronJobList{} },
		),
	}
}
