name: Build Images

on:
  workflow_call:

permissions: read-all

jobs:
  build-images:
    runs-on: ubuntu-24.04
    steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Build Images
        run: |
          make images

      - name: Save Images
        run: |
          make save-images

      - name: Upload Images
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: volcano-images
          path: _output/images
          retention-days: 5
