name: E2E Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - master
    tags:
  pull_request:

permissions: read-all

jobs:
  build-images:
    uses: ./.github/workflows/docker_images.yaml

  e2e-admission:
    needs: build-images
    uses: ./.github/workflows/e2e_admission.yaml

  e2e-cronjob:
    needs: build-images
    uses: ./.github/workflows/e2e_cronjob.yaml

  e2e-dra:
    needs: build-images
    uses: ./.github/workflows/e2e_dra.yml

  e2e-gangevict:
    needs: build-images
    uses: ./.github/workflows/e2e_gangevict.yaml

  e2e-hypernode:
    needs: build-images
    uses: ./.github/workflows/e2e_hypernode.yaml

  e2e-parallel-jobs:
    needs: build-images
    uses: ./.github/workflows/e2e_parallel_jobs.yaml

  e2e-scheduling-actions:
    needs: build-images
    uses: ./.github/workflows/e2e_scheduling_actions.yaml

  e2e-feature-gated:
    needs: build-images
    strategy:
      fail-fast: false
      matrix:
        include:
          - suite_name: E2E about Scheduling Gates
            make_target: e2e-test-schedulinggates
            artifact_name: volcano_e2e_scheduling_gates_logs
            log_directory: e2e-scheduling-gates-logs
          - suite_name: E2E about Unschedulable Job Cache
            make_target: e2e-test-unschedulablejobcache
            artifact_name: volcano_e2e_unschedulable_job_cache_logs
            log_directory: e2e-unschedulable-job-cache-logs
    uses: ./.github/workflows/e2e_feature_gated.yaml
    with:
      suite_name: ${{ matrix.suite_name }}
      make_target: ${{ matrix.make_target }}
      artifact_name: ${{ matrix.artifact_name }}
      log_directory: ${{ matrix.log_directory }}

  e2e-scheduling-basic:
    needs: build-images
    uses: ./.github/workflows/e2e_scheduling_basic.yaml

  e2e-sequence:
    needs: build-images
    uses: ./.github/workflows/e2e_sequence.yaml

  e2e-spark:
    needs: build-images
    uses: ./.github/workflows/e2e_spark.yaml

  e2e-vcctl:
    needs: build-images
    uses: ./.github/workflows/e2e_vcctl.yaml

  e2e-shard:
    needs: build-images
    uses: ./.github/workflows/e2e_shard.yaml
